### ISSUE TITLE
alpha 0.2.0 not working on Windows Blender 4.1.1 and 4.2.0 

### ISSUE THREAD

**Issue by samerps** [Juleinn/IntuitionRF#2]
I've installed the alpha 0.2.0 version in Blender 4.2.0 and Blender 4.1.1 (Windows 11) while it does successfully install, I do not see the Intuition RF panels and I do not see the custom nodes in geometry nodes. 
![image](https://github.com/user-attachments/assets/16e2ea05-b832-47b2-a927-128be3cc831d)
<img width="174" alt="image" src="https://github.com/user-attachments/assets/b2ee80fa-8dbd-4a05-853d-b7dfe793e8c2">

**Comment by Juleinn** [comment]
Hello ! 
Can you confirm that you have linked your OpenEMS installation as per the instructions at the end of the readme file ? 
(cause I see the empty configuration of your plugin in picture #1). 

I think it might be possible to have the plugin download and install all required dependencies (especially on Windows, since OpenEMS comes with built binary), but I haven't developped it.

I haven't updated to 4.2 yet, I'll check. I think the way plugins register to blender changes in 4.2, might be related.

**Comment by samerps** [comment]
ok after linking my openEMS installation I confirm now that it works, thanks!
